base_speed: 0.3
curve_boost: 1.0
curve_speed: 0.1
curve_threshold: 350
d_gain: 0.11 
detection_threshold: 80
max_steer: 0.22
p_gain: 0.2 
steering_threshold: 0.2


# bart
# base_speed: 0.16
# curve_boost: 1.0
# curve_speed: 0.1
# curve_threshold: 350
# d_gain: 0.43   #heading gain
# detection_threshold: 80
# max_steer: 0.22
# p_gain: 0.16    #lateral gain  franky - 0.18, 0.24 glad0us (needs diff right checkpath frames)
# steering_threshold: 0.2