from enum import Enum


class BehaviorState(str, Enum):
    LANE_FOLLOW = "LANE_FOLLOW"
    OBSTACLE_STOP = "OBSTACLE_STOP"
    STOP_WAIT = "STOP_WAIT"
    YIELD_WAIT = "YIELD_WAIT"
    INTERSECTION_DECIDE = "INTERSECTION_DECIDE"
    TURNING = "TURNING"

    CROSSROAD_STOP = "CROSSROAD_STOP"
    CROSSROAD_PEEK_LEFT = "CROSSROAD_PEEK_LEFT"
    CROSSROAD_PEEK_RIGHT = "CROSSROAD_PEEK_RIGHT"
    CROSSROAD_WAIT_VEHICLE = "CROSSROAD_WAIT_VEHICLE"
    CROSSROAD_GO = "CROSSROAD_GO"